export { default as AddIcon } from './Add.svg';
export { default as AddressIcon } from './Address.svg';
export { default as AlertIcon } from './Alert.svg';
export { default as ArrowIcon } from './Arrow.svg';
export { default as CheckIcon } from './Check.svg';
export { default as ChevronIcon } from './Chevron.svg';
export { default as CNPJIcon } from './cnpj.svg';
export { default as DeleteIcon } from './Delete.svg';
export { default as DetailIcon } from './Detail.svg';
export { default as EditIcon } from './Edit.svg';
export { default as EyeIcon } from './Eye.svg';
export { default as LinkedinIcon } from './Linkedin.svg';
export { default as MagnifyingIcon } from './Magnifying.svg';
export { default as MetaIcon } from './Meta.svg';
export { default as SimiliarProductsIcon } from './SimilarProducts.svg';
export { default as StarIcon } from './Star.svg';
export { default as SuccessIcon } from './Success.svg';
export { default as WarningIcon } from './Warning.svg';
export { default as XIcon } from './X.svg';

// export { default as Icon } from './.svg';
