import type { Metadata } from 'next';
import { Lexend, Roboto } from 'next/font/google';
import { PropsWithChildren } from 'react';

import Providers from '@/components/Pages/Providers';
import colors from '@/global/colors';
import './globals.css';

const lexend = Lexend({
  variable: '--font-lexend',
  subsets: ['latin'],
  weight: ['700', '600', '500', '400', '300'],
});

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['700', '600', '500', '400', '300'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} ${roboto.variable} antialiased`}
        style={{ backgroundColor: colors.neutral.background }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
